### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [andresemartinez/chinipage-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by andresemartinez** [comment]
Thanks for reachig out, i uploaded it as a backup so i totally forgot about the license. I updated the README.md an added an MIT License during the weekend. And just to have it in writen, i'm totally ok with adding it to awesome-zsh-plugins. Hope it's useful :)
